services:
  server:
    image: family-recipes:latest
    environment:
      - DATABASE_URL
      - PRIVATE_KEY
      - PUBLIC_KEY
      - KEY_ALGORITHM
      - COOKIE_SECRET
      - DOMAIN
    ports:
      - 4002:8080
    volumes:
      - family-recipes-data:/etc/family-recipes
    depends_on:
      - database
    restart: unless-stopped
  database:
    image: postgres:15
    environment:
      - PGUSER
      - PGPASSWORD
      - PGDATABASE
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - family-recipes-data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  family-recipes-data:
